### PR TITLE
Fix futex page detection

### PR DESCRIPTION
**Pull request by asahilina**
`/proc/<pid>/map_files/*` seems to not allow opening for some reason, which breaks the futex storage match code. Instead, use `/proc/<pid>/maps`, which has the info we need too (should be faster too since it involves fewer syscalls).

This fixes glxgears (Steam is still broken though, but differently now).

### CODE REVIEW

**Comment by WhatAmISupposedToPutHere** [comment]
Sure, but just a question, you are running it as root, right?

**Comment by asahilina** [comment]
I am not, was I supposed to? (That would explain the permission issue, but is there any other reason it has to run as root?)

**Comment by WhatAmISupposedToPutHere** [comment]
Yes, you were supposed to make the binary setuid root and run it that way. But hey, if we can drop the root requirement, that's even better.

**Comment by asahilina** [comment]
FWIW I haven't noticed a difference between root and non-root after this change, so if this was the only real requirement for root, that should now be gone ^^

**Pull request merged**
