### PR TITLE
Use the vDSO to make syscalls

### PR DESCRIPTION
**Pull request by hoshinolina**
Instead of trying to clobber a random instruction in the binary, locate
a syscall instruction in our own vDSO (which is the same for all
processes) and then use that offset into the vDSO for traced processes
to perform syscalls.
    
It seems the old method was unreliable and didn't really work properly
unless the process was in the middle of signal handling, which is why we
had to use a true SIGSTOP (causing the parent to be notified, which is
undesirable). With this method, ptrace::attach() works as intended and
we can avoid the spurious SIGSTOP.

Depends on #1

### CODE REVIEW

**Comment by WhatAmISupposedToPutHere** [comment]
using the vdso is a neat trick, i didn't know that was possible.  There is one change i do not understand though, you have replaced seize with attach, but according to docs, an attach is the same as seize+sigstop. Would that not do the same? Or does attach send a fake sigstop?

**Comment by asahilina** [comment]
I'm not sure I understand ptrace fully myself, but what I was trying to fix is the SIGSTOP leaking into the process and causing an actual stop (for example, causing the parent shell to consider the job stopped and detach).

I looked at what strace -p does (which does not have this issue) and it just uses attach/detach. What stops the SIGSTOP from propagating is not passing it in as a signal into ptrace::cont. However, when I tried that with seize, it didn't work. If I propagated the signal in the first stop event, it bubbled up, and if I didn't, the process didn't seem to actually stop for tracing.

I don't really get it, but there seems to be something subtle about seize and how the process can be stopped after that operation that doesn't happen with attach. I think the SIGSTOP that attach sends is "special" somehow.

**Comment by WhatAmISupposedToPutHere** [comment]
Yeah, i do not fully understand ptrace either (that particular man page is not that well written imo), and just thrown together something that seemed to work on my machine. I now want to experiment a bit with how it all works, so if you need this one merged quickly, could you split the vdso and ptrace into separate ones? (If you are ok with waiting a bit, just leave it as is, ill come back to it after i figure out the whole ptrace thing better)

**Comment by asahilina** [comment]
I was trying to fix the SIGSTOP problem and for that I needed to fix the syscall wonkiness, so no point in merging just one part first ^^. I can wait a bit.

**Comment by WhatAmISupposedToPutHere** [comment]
So, i've played with ptrace a bit, and you might have introduced a behavior change that might be undesirable.
Before:
1. Attach via seize (no effect)
2. Send sigstop
3. Random victim thread enters signal delivery stop, and it is reported via waitpid
4. Forward the signal.
5. All threads enter group stop.
6. Address space surgery happens.
7. All threads are released via sigcont.

After:
1. Attach via attach (causes sigstop to be sent)
2. Random victim thread enters signal delivery stop, and it is reported via waitpid
3. Signal is suppressed, victim thread stays in signal delivery stop, all other threads keep running.
4. Address space surgery happens.
5. Victim thread is released via detach.

As such, with the new code, other threads in the process can keep running, and potentially interfere with the address space surgery that we are doing. It _might_ work out fine, but i would need to be convinced as to why it is ok. As such, you most likely need to stop all  other threads before issuing the syscalls. (There are ways to do it without stopping other threads with seccomp and userfaultfd, but i'm not sure it is worth it).

As with the previous messages, this is based on some experiments and my best attempts at understanding the ptrace manpage, as such, i could be wrong or be missing something.

**Comment by asahilina** [comment]
I think you're right. The question we need to answer is whether in typical usage of the X11 protocol, the futex storage is/can be used after the message is issued (before any reply is processed), or whether it blocks. If it blocks, I argue that it should be safe in practical cases, since effectively the flow we're interested in is already blocked (because we are processing X11 messages synchronously) and it doesn't matter which thread we stop, we are just picking a victim thread so we can inject our syscalls. The actual flow of injected syscalls is:

- mmap() a private page
- open()
- dup2()
- mmap()
- munmap() the private page
- close()

I would argue that in "normal" execution of a process (not starting up, doing weird address space mangling, or about to exec and cleaning up fds, etc.) it is pretty unlikely for a program to do anything that would interfere with these operations from any other thread.

If the blocking behavior is not guaranteed (in practice) and the process might be using the mapped memory or fds already, then we need to stop all threads, though arguably then the current code is also broken because it just replaces the page without doing anything about the contents. At this point I would start advocating for the LD_PRELOAD solution...

**Comment by WhatAmISupposedToPutHere** [comment]
From what i saw, the primary purpose of the futexes is to signal that the x11 server has done whatever needs to be done with the relevant dma-buf, and the client can reuse it. Not sure about blocking however. 

As for replacing the page - it does do something about the content, [here](https://github.com/WhatAmISupposedToPutHere/x112virtgpu/blob/wip-hax/src/main.rs#L1084) the contents of the memfd is copied into the replacement page. In theory it is slightly wrong and should be done after the threads are stopped, but since the x11 server is what writes into the file, it seems to work fine. (still needs to be fixed tho).

My main issue with only stopping one thread is that we do not really know which thread is waiting on the futex (or whether there is one at all), stopping all threads sidesteps the problem since stops restart syscalls, and so the restarted syscall will pick the new page.

And yes, i also think that LD_PRELOAD should be the preferred solution, with the ptrace path kept as a "just in case" for container workloads (not steam, steam runtime works fine with preload).

**Comment by WhatAmISupposedToPutHere** [comment]
Also, some client might send a futex and then just.. do nothing with it, there is a protocol message that also signals that the dma-buf can be reused, and a client can ignore all the futex stuff and only listen to that.

**Comment by asahilina** [comment]
OK, reading some mesa code, I think this isn't safe to do like this. It's *probably* enough to ptrace the X11 thread, but the PID we get from the socket is the top-level PID, not the TID that issued the X11 request, so that isn't useful.

To avoid the SIGSTOP mess, the only safe approach is to ptrace all the threads... so I guess I'll implement that.

**Comment by asahilina** [comment]
I reverted the ptrace changes, so I think you can push this as just the vDSO change. I'll open a separate PR for the attach/SIGSTOP changes.

**Comment by WhatAmISupposedToPutHere** [comment]
Merged manually. (you removed a still-necessary import and i've edited the commit message since part of it no longer applies.)

**Pull request closed without merging**
